branches:
  only:
  - workbench-cd
install: true
git:
  depth: false
script:
  - echo "" > automatic-results/corpus2.conllu
  - cat documents/CF0001.conllu >> automatic-results/corpus2.conllu
  - cat documents/CF0002.conllu >> automatic-results/corpus2.conllu
  - cat automatic-results/corpus2.conllu | grep "sent_id"

deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: "TMcrf7AJbLq1FhnmpfVoJ5nHzaoHBHoRvSLxf/eh/88KcKbzVc5iPniyALYbhPy2Vg2tguD6aJVk0IBWRdLvw34jAQzf0BY5ywG/hY7IkWigOANoIgKzwLhZV/ItfKSUCM4nFIBMxutpbl9s9EzpMzL45NT7O/9ZJTdR/ziQS+IjUKC7OYb+D6Fhtrjfp2pyELI+4Kvdqg10Tg7rzCojq0+mq2IdkN6D+9ekZ9HBveXqUjryVIbtpGiFJRqM6GQvaGNmv0rtQ9vij4CvdO/xFGLRYpkBBBQ9J8xS1/gFqOilo729/RfygNcTFnqFSSmjpFfIboA1O9JdmFWa6kJT+LiVXR2T65+JRckEMr/mWNGifoU9l0rY/RhoF13kMt6PzFHhdRNQn1ymga72lCfL29TLFcUysGE4ZURZTpIbA2amTmQ/mjpKpxxHcJ8EUYQYx9tji3C9teQi/njv+X+J1kYYr7UsMbnmgPZ8iSoDsXNavOWJDjoogUb/1zrcevWEz8C83+3QuztI44iWEokFQVb2oGcYYl1ghFRCvSUFd1HwQleuDUU9Y26qJ9MGvkHzIBeqAh9AH0/XL4Ax/r2LURuXi1epzhA8lWsT0jgOLIQzS6E4uZbRaJPOJViBEtKeyUmy4V1O67hqroiUwzfCUJBn6P6cMTOTQz73niiayrA="
  keep-history: false
  target-branch: automatic-results
  verbose: true
  local-dir: automatic-results
  on:
    branch: workbench-cd
