### 
## Make sure the following values are correctly set up:
  # branches: only:
  # deploy: target-branch: 
  # deploy: local-dir
  # deploy: on: branch:

branches:
  only:
  - workbench-cd
git:
  depth: false

  # we use python because it preinstalls python dependencies which are necessary in scripts/deploy.sh
language: python
python:
  - "2.7"

install:
  - pip install regex
  - cpanm --sudo JSON::Parse
  - cpanm --sudo YAML

script:
  - bash scripts/deploy.sh

deploy:
  ## We are using the Github Pages deploy
  ## https://docs.travis-ci.com/user/deployment/pages/
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: automatic-results # name of the branch to which travis will push
  verbose: true
  local-dir: automatic-results  # directory which will be pushed to target-branch
  on:
    branch: workbench-cd

