branches:
  only:
  - workbench-cd
install: true
git:
  depth: false
script:
  - echo "" > automatic-results/corpus2.conllu
  - cat documents/CF0001.conllu >> automatic-results/corpus2.conllu
  - cat documents/CF0002.conllu >> automatic-results/corpus2.conllu
  - cat automatic-results/corpus2.conllu | grep "sent_id"

deploy:
  provider: pages
  skip-cleanup: true
  gh-token:
    secure: "jPbmsxrSV9Vi061HFeu9OwyvTJuJqyBsvX1rwY2HQUjvdOob1vhUJe3Ax6IHTZkaQCJF8mZvm/e/aM0OZ0HrS38f8mbN8+/a2DDO4pnfhT6zk9CUfWAcnH/aOzx7eoBRVm8XF8RsU4zCwvwgxMzIVXcX8gG2hPKo+6J0Bligf7k0M2ayKgM8TfBvoASesm+ont2qUHAtbXmv0rtQ9Rz4vQ/DzsPP0TzWKgqoDuC9uoIwzb8uokPre0/0kEcbPhiTG4jMw3q5c3BNTzuGFMRiO0Hb50L8vkXzuzNsWlruljDI7XBInpjeEV7pQf2EdChvL6XYS6kT5Zg+hks+gxew9PwF1QREUq3n+ffcrArSC1Eb8v6oh6mtpZaD3qf/7yuUYZVohfGLgE+xJK0lifzPcSAXwJj+cTr2bo/lcfHWEspONy0ZN5WYFZ8IMli412U5Gd4S8SfWIZGayTRkfRCrHNfZcxgoUkugA14Ta/15X2JbIiyJSR3P7vEJQC44xng9Axk72iemLJI8/xxuDjWkzQfxaMw64AWpudtzupnJcgSC1IskHd3mZJDaBDyat7bxwyMLJWRyjqUzhcG8x3R0rQE4nazJcBJOjf8br+VcVIaY+COPWKhT+/kJGp+dFuxcN2T6BkcXSsSv1Jgqz+Mfz1ZuL4VgPrJ6KqHtwdvxhXE="
  github-token:
    secure: "jPbmsxrSV9Vi061HFeu9OwyvTJuJqyBsvX1rwY2HQUjvdOob1vhUJe3Ax6IHTZkaQCJF8mZvm/e/aM0OZ0HrS38f8mbN8+/a2DDO4pnfhT6zk9CUfWAcnH/aOzx7eoBRVm8XF8RsU4zCwvwgxMzIVXcX8gG2hPKo+6J0Bligf7k0M2ayKgM8TfBvoASesm+ont2qUHAtbXmv0rtQ9Rz4vQ/DzsPP0TzWKgqoDuC9uoIwzb8uokPre0/0kEcbPhiTG4jMw3q5c3BNTzuGFMRiO0Hb50L8vkXzuzNsWlruljDI7XBInpjeEV7pQf2EdChvL6XYS6kT5Zg+hks+gxew9PwF1QREUq3n+ffcrArSC1Eb8v6oh6mtpZaD3qf/7yuUYZVohfGLgE+xJK0lifzPcSAXwJj+cTr2bo/lcfHWEspONy0ZN5WYFZ8IMli412U5Gd4S8SfWIZGayTRkfRCrHNfZcxgoUkugA14Ta/15X2JbIiyJSR3P7vEJQC44xng9Axk72iemLJI8/xxuDjWkzQfxaMw64AWpudtzupnJcgSC1IskHd3mZJDaBDyat7bxwyMLJWRyjqUzhcG8x3R0rQE4nazJcBJOjf8br+VcVIaY+COPWKhT+/kJGp+dFuxcN2T6BkcXSsSv1Jgqz+Mfz1ZuL4VgPrJ6KqHtwdvxhXE="
  keep-history: false
  target-branch: automatic-results
  verbose: true
  local-dir: automatic-results
  on:
    branch: workbench-cd
