branches:
  only:
  - workbench-cd
install: true
git:
  depth: false
script:
  - echo "" > automatic-results/corpus2.conllu
  - cat documents/CF0001.conllu >> automatic-results/corpus2.conllu
  - cat documents/CF0002.conllu >> automatic-results/corpus2.conllu
  - cat automatic-results/corpus2.conllu | grep "sent_id"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: automatic-results
  verbose: true
  local-dir: automatic-results
  on:
    branch: workbench-cd

    # useless commit just in order to trigger travis
