branches:
  only:
  - workbench-cd
git:
  depth: false

  # we use python because it preinstalls python dependencies which are necessary in scripts/deploy.sh
language: python
python:
  - "2.7"

install:
  - pip install regex
  - cpanm --sudo JSON::Parse
  - cpanm --sudo YAML

script:
  - bash scripts/deploy.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: automatic-results
  verbose: true
  local-dir: automatic-results
  on:
    branch: workbench-cd

