branches:
  only:
  - workbench-cd
language: python
python:
  - "2.7"
install:
  - pip install regex
git:
  depth: false
script:
  - bash scripts/deploy.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: automatic-results
  verbose: true
  local-dir: automatic-results
  on:
    branch: workbench-cd

